### ISSUE TITLE
Call Activity error

### ISSUE THREAD

**Issue by javabbt** [mesibo/ui-modules-android#1]
i get this error while launching the call activity

03-04 16:15:21.346 18219-18219/picstar.kimbogames.picstar E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{picstar.kimbogames.picstar/picstar.kimbogames.picstar.calls.CallActivity}: java.lang.NullPointerException: Attempt to write to field 'com.mesibo.calls.api.MesiboCallActivity com.mesibo.calls.api.MesiboCall$CallProperties.activity' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.access$900(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5835)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: java.lang.NullPointerException: Attempt to write to field 'com.mesibo.calls.api.MesiboCallActivity com.mesibo.calls.api.MesiboCall$CallProperties.activity' on a null object reference
        at com.mesibo.calls.api.k.onCreate(Unknown Source)
        at picstar.kimbogames.picstar.calls.CallActivity.onCreate(CallActivity.java:21)

**Comment by mesibo** [comment]
https://mesibo.com/documentation/faq/support/#what-information-should-i-provide-when-requesting-technical-support
